/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appImageEditorRouteImport } from './routes/(app)/image-editor'
import { Route as appStickyNotesRouteRouteImport } from './routes/(app)/sticky-notes/route'
import { Route as appStickyNotesIndexRouteImport } from './routes/(app)/sticky-notes/index'
import { Route as appDocsIndexRouteImport } from './routes/(app)/docs/index'
import { Route as appStickyNotesDateRouteImport } from './routes/(app)/sticky-notes/$date'
import { Route as appDocsIdRouteImport } from './routes/(app)/docs/$id'
import { Route as authApiAuthLoginRouteImport } from './routes/(auth)/api.auth.login'
import { Route as authApiAuthCallbackGithubRouteImport } from './routes/(auth)/api.auth.callback.github'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appImageEditorRoute = appImageEditorRouteImport.update({
  id: '/image-editor',
  path: '/image-editor',
  getParentRoute: () => appRouteRoute,
} as any)
const appStickyNotesRouteRoute = appStickyNotesRouteRouteImport.update({
  id: '/sticky-notes',
  path: '/sticky-notes',
  getParentRoute: () => appRouteRoute,
} as any)
const appStickyNotesIndexRoute = appStickyNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appStickyNotesRouteRoute,
} as any)
const appDocsIndexRoute = appDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => appRouteRoute,
} as any)
const appStickyNotesDateRoute = appStickyNotesDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => appStickyNotesRouteRoute,
} as any)
const appDocsIdRoute = appDocsIdRouteImport.update({
  id: '/docs/$id',
  path: '/docs/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const authApiAuthLoginRoute = authApiAuthLoginRouteImport.update({
  id: '/(auth)/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authApiAuthCallbackGithubRoute =
  authApiAuthCallbackGithubRouteImport.update({
    id: '/(auth)/api/auth/callback/github',
    path: '/api/auth/callback/github',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/sticky-notes': typeof appStickyNotesRouteRouteWithChildren
  '/image-editor': typeof appImageEditorRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/docs/$id': typeof appDocsIdRoute
  '/sticky-notes/$date': typeof appStickyNotesDateRoute
  '/docs': typeof appDocsIndexRoute
  '/sticky-notes/': typeof appStickyNotesIndexRoute
  '/api/auth/login': typeof authApiAuthLoginRoute
  '/api/auth/callback/github': typeof authApiAuthCallbackGithubRoute
}
export interface FileRoutesByTo {
  '/image-editor': typeof appImageEditorRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/docs/$id': typeof appDocsIdRoute
  '/sticky-notes/$date': typeof appStickyNotesDateRoute
  '/docs': typeof appDocsIndexRoute
  '/sticky-notes': typeof appStickyNotesIndexRoute
  '/api/auth/login': typeof authApiAuthLoginRoute
  '/api/auth/callback/github': typeof authApiAuthCallbackGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/sticky-notes': typeof appStickyNotesRouteRouteWithChildren
  '/(app)/image-editor': typeof appImageEditorRoute
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/docs/$id': typeof appDocsIdRoute
  '/(app)/sticky-notes/$date': typeof appStickyNotesDateRoute
  '/(app)/docs/': typeof appDocsIndexRoute
  '/(app)/sticky-notes/': typeof appStickyNotesIndexRoute
  '/(auth)/api/auth/login': typeof authApiAuthLoginRoute
  '/(auth)/api/auth/callback/github': typeof authApiAuthCallbackGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sticky-notes'
    | '/image-editor'
    | '/login'
    | '/'
    | '/docs/$id'
    | '/sticky-notes/$date'
    | '/docs'
    | '/sticky-notes/'
    | '/api/auth/login'
    | '/api/auth/callback/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/image-editor'
    | '/login'
    | '/'
    | '/docs/$id'
    | '/sticky-notes/$date'
    | '/docs'
    | '/sticky-notes'
    | '/api/auth/login'
    | '/api/auth/callback/github'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/sticky-notes'
    | '/(app)/image-editor'
    | '/(auth)/login'
    | '/(app)/'
    | '/(app)/docs/$id'
    | '/(app)/sticky-notes/$date'
    | '/(app)/docs/'
    | '/(app)/sticky-notes/'
    | '/(auth)/api/auth/login'
    | '/(auth)/api/auth/callback/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authApiAuthLoginRoute: typeof authApiAuthLoginRoute
  authApiAuthCallbackGithubRoute: typeof authApiAuthCallbackGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/image-editor': {
      id: '/(app)/image-editor'
      path: '/image-editor'
      fullPath: '/image-editor'
      preLoaderRoute: typeof appImageEditorRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sticky-notes': {
      id: '/(app)/sticky-notes'
      path: '/sticky-notes'
      fullPath: '/sticky-notes'
      preLoaderRoute: typeof appStickyNotesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sticky-notes/': {
      id: '/(app)/sticky-notes/'
      path: '/'
      fullPath: '/sticky-notes/'
      preLoaderRoute: typeof appStickyNotesIndexRouteImport
      parentRoute: typeof appStickyNotesRouteRoute
    }
    '/(app)/docs/': {
      id: '/(app)/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof appDocsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/sticky-notes/$date': {
      id: '/(app)/sticky-notes/$date'
      path: '/$date'
      fullPath: '/sticky-notes/$date'
      preLoaderRoute: typeof appStickyNotesDateRouteImport
      parentRoute: typeof appStickyNotesRouteRoute
    }
    '/(app)/docs/$id': {
      id: '/(app)/docs/$id'
      path: '/docs/$id'
      fullPath: '/docs/$id'
      preLoaderRoute: typeof appDocsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/api/auth/login': {
      id: '/(auth)/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof authApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/api/auth/callback/github': {
      id: '/(auth)/api/auth/callback/github'
      path: '/api/auth/callback/github'
      fullPath: '/api/auth/callback/github'
      preLoaderRoute: typeof authApiAuthCallbackGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appStickyNotesRouteRouteChildren {
  appStickyNotesDateRoute: typeof appStickyNotesDateRoute
  appStickyNotesIndexRoute: typeof appStickyNotesIndexRoute
}

const appStickyNotesRouteRouteChildren: appStickyNotesRouteRouteChildren = {
  appStickyNotesDateRoute: appStickyNotesDateRoute,
  appStickyNotesIndexRoute: appStickyNotesIndexRoute,
}

const appStickyNotesRouteRouteWithChildren =
  appStickyNotesRouteRoute._addFileChildren(appStickyNotesRouteRouteChildren)

interface appRouteRouteChildren {
  appStickyNotesRouteRoute: typeof appStickyNotesRouteRouteWithChildren
  appImageEditorRoute: typeof appImageEditorRoute
  appIndexRoute: typeof appIndexRoute
  appDocsIdRoute: typeof appDocsIdRoute
  appDocsIndexRoute: typeof appDocsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appStickyNotesRouteRoute: appStickyNotesRouteRouteWithChildren,
  appImageEditorRoute: appImageEditorRoute,
  appIndexRoute: appIndexRoute,
  appDocsIdRoute: appDocsIdRoute,
  appDocsIndexRoute: appDocsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authApiAuthLoginRoute: authApiAuthLoginRoute,
  authApiAuthCallbackGithubRoute: authApiAuthCallbackGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
